version: '2'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./scraper:/app
      - shared-volume:/app/shared

  nextjs:
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:3000
    volumes:
      - ./nextjs:/app
      - shared-volume:/app/shared

volumes:
  shared-volume: