version: '2'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - ./scraper:/app
      - ./status:/app/status
      - db-module:/app/src/db

  nextjs:
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - 8080:3000
    volumes:
      - ./nextjs:/app
      - ./status:/app/status
      - db-module:/app/db

volumes:
  db-module: