version: '3'
services:
  postgres:
    container_name: ${DB_HOST}
    image: postgres
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}


  app:
    container_name: app
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}
      - SC_TARGET_NUMBER=${SC_TARGET_NUMBER}
    depends_on:
      - postgres
    ports: 
      - 8080:8080
    # volumes:
    #   - ./nextjs:/app


  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      - app
    # volumes:
    #   - ./scraper:/app

